export interface BiblicalWord {
  /** Forma exibida, com acentos */
  palavra: string;
  /** Referência bíblica */
  referencia: string;
  /** Dica/curiosidade revelada ao jogador */
  dica: string;
}

/**
 * Banco de palavras do modo diário (4 a 8 letras, sem contar acentos).
 * A ordem é embaralhada deterministicamente em daily.ts — adicionar
 * novas palavras ao FINAL da lista não altera os dias já sorteados.
 */
export const WORDS: BiblicalWord[] = [
  // ===== Personagens do Antigo Testamento =====
  { palavra: "ADÃO", referencia: "Gênesis 2:20", dica: "O primeiro homem, formado do pó da terra" },
  { palavra: "CAIM", referencia: "Gênesis 4:8", dica: "Matou seu irmão por inveja" },
  { palavra: "ABEL", referencia: "Gênesis 4:4", dica: "Pastor de ovelhas cuja oferta agradou a Deus" },
  { palavra: "SETE", referencia: "Gênesis 4:25", dica: "Filho de Adão nascido depois da morte de Abel" },
  { palavra: "ENOQUE", referencia: "Gênesis 5:24", dica: "Andou com Deus e foi arrebatado sem ver a morte" },
  { palavra: "ABRAÃO", referencia: "Gênesis 17:5", dica: "Pai de uma multidão de nações" },
  { palavra: "SARA", referencia: "Gênesis 17:15", dica: "Riu ao ouvir que teria um filho na velhice" },
  { palavra: "AGAR", referencia: "Gênesis 16:1", dica: "Serva egípcia de Sara, mãe de Ismael" },
  { palavra: "ISMAEL", referencia: "Gênesis 16:11", dica: "Filho de Abraão com a serva egípcia" },
  { palavra: "ISAQUE", referencia: "Gênesis 22:2", dica: "Filho da promessa, quase sacrificado no monte Moriá" },
  { palavra: "REBECA", referencia: "Gênesis 24:67", dica: "Deu de beber aos camelos e tornou-se esposa de Isaque" },
  { palavra: "JACÓ", referencia: "Gênesis 28:12", dica: "Sonhou com uma escada que tocava o céu" },
  { palavra: "ESAÚ", referencia: "Gênesis 25:25", dica: "Vendeu a primogenitura por um prato de lentilhas" },
  { palavra: "RAQUEL", referencia: "Gênesis 29:18", dica: "Jacó trabalhou catorze anos para se casar com ela" },
  { palavra: "LABÃO", referencia: "Gênesis 29:25", dica: "Sogro que enganou Jacó na noite do casamento" },
  { palavra: "JOSÉ", referencia: "Gênesis 37:3", dica: "Recebeu do pai uma túnica colorida e sonhava sonhos" },
  { palavra: "BENJAMIM", referencia: "Gênesis 35:18", dica: "O caçula dos doze filhos de Jacó" },
  { palavra: "JUDÁ", referencia: "Gênesis 49:10", dica: "Tribo da qual descende o Messias" },
  { palavra: "LEVI", referencia: "Êxodo 32:26", dica: "Tribo separada para o serviço do santuário" },
  { palavra: "SIMEÃO", referencia: "Gênesis 34:25", dica: "Segundo filho de Jacó e Lia" },
  { palavra: "POTIFAR", referencia: "Gênesis 39:1", dica: "Oficial de Faraó que comprou José como escravo" },
  { palavra: "FARAÓ", referencia: "Êxodo 5:2", dica: "Rei do Egito que endureceu o coração" },
  { palavra: "MOISÉS", referencia: "Êxodo 2:10", dica: "Tirado das águas, libertou o povo de Israel do Egito" },
  { palavra: "AARÃO", referencia: "Êxodo 4:14", dica: "Irmão de Moisés e primeiro sumo sacerdote" },
  { palavra: "MIRIÃ", referencia: "Êxodo 15:20", dica: "Profetisa que cantou e dançou após a travessia do mar" },
  { palavra: "JETRO", referencia: "Êxodo 18:1", dica: "Sogro de Moisés, sacerdote de Midiã" },
  { palavra: "ZÍPORA", referencia: "Êxodo 2:21", dica: "Esposa midianita de Moisés" },
  { palavra: "JOSUÉ", referencia: "Josué 1:9", dica: "Sucedeu Moisés e conquistou a terra prometida" },
  { palavra: "CALEBE", referencia: "Números 13:30", dica: "Espia corajoso que confiou na promessa de Deus" },
  { palavra: "BALAÃO", referencia: "Números 22:28", dica: "Profeta repreendido pela própria jumenta" },
  { palavra: "RAABE", referencia: "Josué 2:1", dica: "Escondeu os espias em Jericó e foi salva" },
  { palavra: "DÉBORA", referencia: "Juízes 4:4", dica: "Profetisa e juíza que julgava debaixo de uma palmeira" },
  { palavra: "GIDEÃO", referencia: "Juízes 7:7", dica: "Venceu os midianitas com apenas trezentos homens" },
  { palavra: "SANSÃO", referencia: "Juízes 16:17", dica: "Sua força estava nos cabelos" },
  { palavra: "DALILA", referencia: "Juízes 16:19", dica: "Descobriu o segredo da força de Sansão" },
  { palavra: "RUTE", referencia: "Rute 1:16", dica: "Moabita fiel: 'aonde quer que fores, irei eu'" },
  { palavra: "NOEMI", referencia: "Rute 1:20", dica: "Sogra de Rute, pediu para ser chamada de Mara" },
  { palavra: "BOAZ", referencia: "Rute 2:1", dica: "Resgatador que se casou com Rute" },
  { palavra: "SAMUEL", referencia: "1 Samuel 3:10", dica: "Ouviu a voz de Deus ainda menino no templo" },
  { palavra: "SAUL", referencia: "1 Samuel 9:2", dica: "O primeiro rei de Israel" },
  { palavra: "DAVI", referencia: "1 Samuel 17:45", dica: "Pastor que venceu um gigante com uma funda" },
  { palavra: "GOLIAS", referencia: "1 Samuel 17:4", dica: "Gigante filisteu derrotado por um jovem pastor" },
  { palavra: "JESSÉ", referencia: "1 Samuel 16:1", dica: "Pai de Davi, morador de Belém" },
  { palavra: "JÔNATAS", referencia: "1 Samuel 18:1", dica: "Filho de Saul e melhor amigo de Davi" },
  { palavra: "MICAL", referencia: "1 Samuel 18:27", dica: "Filha de Saul, primeira esposa de Davi" },
  { palavra: "NATÃ", referencia: "2 Samuel 12:7", dica: "Profeta que confrontou Davi: 'Tu és este homem!'" },
  { palavra: "ABSALÃO", referencia: "2 Samuel 18:9", dica: "Filho rebelde de Davi, ficou preso pelos cabelos" },
  { palavra: "SALOMÃO", referencia: "1 Reis 3:12", dica: "Pediu sabedoria a Deus e construiu o templo" },
  { palavra: "ACABE", referencia: "1 Reis 16:30", dica: "Rei ímpio de Israel, marido de Jezabel" },
  { palavra: "JEZABEL", referencia: "1 Reis 19:2", dica: "Rainha que perseguiu os profetas do Senhor" },
  { palavra: "ELIAS", referencia: "1 Reis 18:38", dica: "Desafiou os profetas de Baal no monte Carmelo" },
  { palavra: "ELISEU", referencia: "2 Reis 2:9", dica: "Pediu porção dobrada do espírito de seu mestre" },
  { palavra: "NAAMÃ", referencia: "2 Reis 5:14", dica: "General sírio curado da lepra no rio Jordão" },
  { palavra: "JOSIAS", referencia: "2 Reis 23:25", dica: "Rei menino que restaurou a adoração em Judá" },
  { palavra: "EZEQUIAS", referencia: "2 Reis 20:5", dica: "Rei que ganhou quinze anos a mais de vida" },
  { palavra: "ESDRAS", referencia: "Esdras 7:10", dica: "Escriba que ensinou a Lei ao povo no retorno do exílio" },
  { palavra: "NEEMIAS", referencia: "Neemias 2:17", dica: "Reconstruiu os muros de Jerusalém" },
  { palavra: "ESTER", referencia: "Ester 4:14", dica: "Rainha que salvou seu povo 'para um momento como este'" },
  { palavra: "HAMÃ", referencia: "Ester 7:10", dica: "Tramou contra os judeus e morreu na própria forca" },
  { palavra: "VASTI", referencia: "Ester 1:12", dica: "Rainha deposta antes de Ester" },
  { palavra: "CIRO", referencia: "Esdras 1:1", dica: "Rei persa que autorizou a volta dos judeus do exílio" },
  { palavra: "ISAÍAS", referencia: "Isaías 6:8", dica: "Profeta que disse: 'Eis-me aqui, envia-me a mim'" },
  { palavra: "JEREMIAS", referencia: "Jeremias 1:5", dica: "O profeta que chorava por Jerusalém" },
  { palavra: "EZEQUIEL", referencia: "Ezequiel 37:4", dica: "Profetizou a um vale de ossos secos" },
  { palavra: "DANIEL", referencia: "Daniel 6:22", dica: "Saiu ileso da cova dos leões" },
  { palavra: "SADRAQUE", referencia: "Daniel 3:25", dica: "Um dos três jovens lançados na fornalha ardente" },
  { palavra: "MESAQUE", referencia: "Daniel 3:25", dica: "Companheiro de Daniel salvo da fornalha" },
  { palavra: "ABEDNEGO", referencia: "Daniel 3:25", dica: "O terceiro jovem que não se curvou à estátua" },
  { palavra: "JONAS", referencia: "Jonas 1:17", dica: "Passou três dias no ventre de um grande peixe" },
  { palavra: "OSEIAS", referencia: "Oseias 1:2", dica: "Profeta cujo casamento ilustrou o amor fiel de Deus" },
  { palavra: "JOEL", referencia: "Joel 2:28", dica: "Profetizou o derramamento do Espírito sobre toda carne" },
  { palavra: "AMÓS", referencia: "Amós 1:1", dica: "Boiadeiro de Tecoa chamado a profetizar" },
  { palavra: "MIQUEIAS", referencia: "Miqueias 5:2", dica: "Anunciou que o Messias nasceria em Belém" },
  { palavra: "NAUM", referencia: "Naum 1:7", dica: "Profetizou contra Nínive: 'O Senhor é bom, uma fortaleza'" },
  { palavra: "AGEU", referencia: "Ageu 1:8", dica: "Exortou o povo a reconstruir o templo" },
  { palavra: "SOFONIAS", referencia: "Sofonias 3:17", dica: "Profetizou que Deus se alegra sobre nós com cânticos" },
  { palavra: "ZACARIAS", referencia: "Zacarias 9:9", dica: "Viu o rei vindo humilde, montado num jumentinho" },

  // ===== Personagens do Novo Testamento =====
  { palavra: "JESUS", referencia: "Mateus 1:21", dica: "O nome que está acima de todo nome" },
  { palavra: "MARIA", referencia: "Lucas 1:30", dica: "Achou graça diante de Deus e gerou o Salvador" },
  { palavra: "MARTA", referencia: "Lucas 10:41", dica: "Ocupava-se com muitas coisas enquanto a irmã ouvia Jesus" },
  { palavra: "PEDRO", referencia: "Mateus 16:18", dica: "A 'pedra' que negou Jesus três vezes antes do galo cantar" },
  { palavra: "ANDRÉ", referencia: "João 1:40", dica: "Pescador que levou seu irmão Simão até Jesus" },
  { palavra: "TIAGO", referencia: "Marcos 3:17", dica: "Filho de Zebedeu, um dos 'filhos do trovão'" },
  { palavra: "JOÃO", referencia: "João 13:23", dica: "O discípulo amado, autor do Apocalipse" },
  { palavra: "FELIPE", referencia: "João 1:45", dica: "Disse a Natanael: 'Vem e vê'" },
  { palavra: "TOMÉ", referencia: "João 20:27", dica: "Só creu depois de ver as marcas dos cravos" },
  { palavra: "MATEUS", referencia: "Mateus 9:9", dica: "Cobrador de impostos chamado a seguir Jesus" },
  { palavra: "JUDAS", referencia: "Mateus 26:15", dica: "Traiu o Mestre por trinta moedas de prata" },
  { palavra: "SIMÃO", referencia: "Lucas 23:26", dica: "O cireneu obrigado a carregar a cruz de Jesus" },
  { palavra: "MARCOS", referencia: "Atos 12:25", dica: "Autor do segundo Evangelho, companheiro de Paulo e Barnabé" },
  { palavra: "LUCAS", referencia: "Colossenses 4:14", dica: "O médico amado que escreveu um Evangelho e Atos" },
  { palavra: "PAULO", referencia: "Atos 13:9", dica: "De perseguidor a apóstolo dos gentios" },
  { palavra: "SAULO", referencia: "Atos 9:4", dica: "Ouviu no caminho de Damasco: 'por que me persegues?'" },
  { palavra: "BARNABÉ", referencia: "Atos 4:36", dica: "Seu nome significa 'filho da consolação'" },
  { palavra: "SILAS", referencia: "Atos 16:25", dica: "Cantava louvores na prisão com Paulo à meia-noite" },
  { palavra: "TIMÓTEO", referencia: "1 Timóteo 4:12", dica: "Jovem pastor: 'ninguém despreze a tua mocidade'" },
  { palavra: "TITO", referencia: "Tito 1:5", dica: "Recebeu carta de Paulo e organizou a igreja em Creta" },
  { palavra: "ESTÊVÃO", referencia: "Atos 7:59", dica: "O primeiro mártir da igreja" },
  { palavra: "ZAQUEU", referencia: "Lucas 19:4", dica: "Subiu numa árvore para ver Jesus passar" },
  { palavra: "LÁZARO", referencia: "João 11:43", dica: "Saiu do túmulo depois de quatro dias" },
  { palavra: "MADALENA", referencia: "João 20:16", dica: "A primeira a ver o Senhor ressuscitado" },
  { palavra: "HERODES", referencia: "Mateus 2:16", dica: "Rei que mandou matar os meninos de Belém" },
  { palavra: "PILATOS", referencia: "Mateus 27:24", dica: "Lavou as mãos diante da multidão" },
  { palavra: "CAIFÁS", referencia: "João 18:14", dica: "Sumo sacerdote no julgamento de Jesus" },
  { palavra: "BARRABÁS", referencia: "Mateus 27:21", dica: "O prisioneiro solto no lugar de Jesus" },
  { palavra: "PRISCILA", referencia: "Atos 18:26", dica: "Com seu marido Áquila, ensinou o caminho a Apolo" },
  { palavra: "ÁQUILA", referencia: "Atos 18:2", dica: "Fazedor de tendas, marido de Priscila" },
  { palavra: "LÍDIA", referencia: "Atos 16:14", dica: "Vendedora de púrpura, primeira convertida na Europa" },
  { palavra: "DORCAS", referencia: "Atos 9:36", dica: "Ressuscitada por Pedro, fazia roupas para os pobres" },
  { palavra: "CORNÉLIO", referencia: "Atos 10:1", dica: "Centurião que recebeu Pedro e o Espírito Santo" },
  { palavra: "ANANIAS", referencia: "Atos 9:17", dica: "Impôs as mãos sobre Saulo para que voltasse a ver" },
  { palavra: "ONÉSIMO", referencia: "Filemom 1:10", dica: "Escravo fugitivo que se tornou irmão amado" },
  { palavra: "BATISTA", referencia: "Mateus 3:1", dica: "Apelido do João que pregava no deserto" },

  // ===== Lugares =====
  { palavra: "ÉDEN", referencia: "Gênesis 2:8", dica: "O jardim onde tudo começou" },
  { palavra: "BABEL", referencia: "Gênesis 11:9", dica: "Torre onde as línguas foram confundidas" },
  { palavra: "SODOMA", referencia: "Gênesis 19:24", dica: "Cidade destruída por fogo e enxofre" },
  { palavra: "CANAÃ", referencia: "Êxodo 3:8", dica: "Terra que mana leite e mel" },
  { palavra: "EGITO", referencia: "Êxodo 1:8", dica: "Terra da escravidão de Israel por 400 anos" },
  { palavra: "GÓSEN", referencia: "Gênesis 47:27", dica: "Região do Egito onde Israel habitou" },
  { palavra: "SINAI", referencia: "Êxodo 19:20", dica: "Monte onde Moisés recebeu as tábuas da Lei" },
  { palavra: "HOREBE", referencia: "Êxodo 3:1", dica: "O monte de Deus, onde a sarça ardia" },
  { palavra: "MIDIÃ", referencia: "Êxodo 2:15", dica: "Terra para onde Moisés fugiu de Faraó" },
  { palavra: "MOABE", referencia: "Rute 1:1", dica: "Terra natal de Rute" },
  { palavra: "ARARATE", referencia: "Gênesis 8:4", dica: "Montes onde a arca repousou" },
  { palavra: "JERICÓ", referencia: "Josué 6:20", dica: "Suas muralhas caíram ao som das trombetas" },
  { palavra: "BETEL", referencia: "Gênesis 28:19", dica: "'Casa de Deus', onde Jacó sonhou com a escada" },
  { palavra: "HEBROM", referencia: "Gênesis 23:19", dica: "Cidade onde Abraão sepultou Sara" },
  { palavra: "SIÃO", referencia: "Salmos 2:6", dica: "O monte santo, símbolo de Jerusalém" },
  { palavra: "SAMARIA", referencia: "João 4:4", dica: "Região da mulher que conversou com Jesus junto ao poço" },
  { palavra: "BELÉM", referencia: "Mateus 2:1", dica: "A pequena cidade onde o Salvador nasceu" },
  { palavra: "NAZARÉ", referencia: "Mateus 2:23", dica: "'Pode vir algo de bom de lá?'" },
  { palavra: "GALILEIA", referencia: "Mateus 4:18", dica: "Região do mar onde Jesus chamou os pescadores" },
  { palavra: "JORDÃO", referencia: "Mateus 3:13", dica: "Rio onde Jesus foi batizado" },
  { palavra: "CANÁ", referencia: "João 2:1", dica: "Cidade do primeiro milagre: água em vinho" },
  { palavra: "GÓLGOTA", referencia: "João 19:17", dica: "'Lugar da Caveira', onde a cruz foi fincada" },
  { palavra: "CALVÁRIO", referencia: "Lucas 23:33", dica: "Nome latino do monte da crucificação" },
  { palavra: "EMAÚS", referencia: "Lucas 24:13", dica: "No caminho até lá, dois discípulos andaram com o Ressuscitado" },
  { palavra: "DAMASCO", referencia: "Atos 9:3", dica: "Saulo foi transformado a caminho desta cidade" },
  { palavra: "TARSO", referencia: "Atos 9:11", dica: "Cidade natal do apóstolo Paulo" },
  { palavra: "CORINTO", referencia: "Atos 18:1", dica: "Cidade grega que recebeu duas cartas de Paulo" },
  { palavra: "ÉFESO", referencia: "Atos 19:1", dica: "Paulo viveu ali três anos; recebeu uma carta e um aviso no Apocalipse" },
  { palavra: "ROMA", referencia: "Atos 28:16", dica: "Capital do império, destino final de Paulo" },
  { palavra: "PATMOS", referencia: "Apocalipse 1:9", dica: "Ilha onde João recebeu a revelação" },
  { palavra: "NÍNIVE", referencia: "Jonas 3:5", dica: "A grande cidade que se arrependeu com a pregação de Jonas" },

  // ===== Conceitos e termos =====
  { palavra: "DEUS", referencia: "Gênesis 1:1", dica: "No princípio, Ele criou os céus e a terra" },
  { palavra: "AMOR", referencia: "1 Coríntios 13:13", dica: "A maior entre a fé e a esperança" },
  { palavra: "VIDA", referencia: "João 14:6", dica: "Jesus é o caminho, a verdade e..." },
  { palavra: "VERBO", referencia: "João 1:1", dica: "No princípio era... e Ele se fez carne" },
  { palavra: "GRAÇA", referencia: "Efésios 2:8", dica: "Pela qual somos salvos, mediante a fé" },
  { palavra: "GLÓRIA", referencia: "Romanos 11:36", dica: "A Ele seja dada para todo o sempre" },
  { palavra: "PECADO", referencia: "Romanos 6:23", dica: "Seu salário é a morte" },
  { palavra: "PERDÃO", referencia: "Mateus 18:22", dica: "Setenta vezes sete" },
  { palavra: "ALIANÇA", referencia: "Gênesis 9:13", dica: "O arco-íris é o sinal da primeira" },
  { palavra: "PROFETA", referencia: "Deuteronômio 18:18", dica: "Porta-voz de Deus ao povo" },
  { palavra: "APÓSTOLO", referencia: "Efésios 4:11", dica: "'Enviado' — Jesus escolheu doze" },
  { palavra: "BATISMO", referencia: "Romanos 6:4", dica: "Sepultados com Cristo nas águas" },
  { palavra: "ORAÇÃO", referencia: "1 Tessalonicenses 5:17", dica: "Orai sem cessar" },
  { palavra: "JEJUM", referencia: "Mateus 6:17", dica: "Quando praticares, unge a cabeça e lava o rosto" },
  { palavra: "DÍZIMO", referencia: "Malaquias 3:10", dica: "Trazei-os todos à casa do tesouro" },
  { palavra: "LOUVOR", referencia: "Salmos 150:6", dica: "Tudo quanto tem fôlego, louve ao Senhor" },
  { palavra: "ADORAÇÃO", referencia: "João 4:24", dica: "Em espírito e em verdade" },
  { palavra: "MILAGRE", referencia: "João 2:11", dica: "O primeiro foi numa festa de casamento" },
  { palavra: "PARÁBOLA", referencia: "Mateus 13:34", dica: "Jesus ensinava as multidões por meio delas" },
  { palavra: "SALVAÇÃO", referencia: "Atos 4:12", dica: "Não há em nenhum outro nome" },
  { palavra: "REDENÇÃO", referencia: "Efésios 1:7", dica: "Temos por meio do Seu sangue" },
  { palavra: "ESPÍRITO", referencia: "Atos 2:4", dica: "Desceu como línguas de fogo no Pentecostes" },
  { palavra: "CRIAÇÃO", referencia: "Gênesis 1:31", dica: "Deus viu tudo o que fez, e era muito bom" },
  { palavra: "DILÚVIO", referencia: "Gênesis 7:12", dica: "Quarenta dias e quarenta noites de chuva" },
  { palavra: "MESSIAS", referencia: "João 4:25", dica: "O Ungido prometido, que em grego é 'Cristo'" },
  { palavra: "EMANUEL", referencia: "Mateus 1:23", dica: "Significa 'Deus conosco'" },
  { palavra: "HOSANA", referencia: "Mateus 21:9", dica: "Grito da multidão na entrada triunfal" },
  { palavra: "ALELUIA", referencia: "Salmos 146:1", dica: "Expressão de louvor: 'Louvai ao Senhor'" },
  { palavra: "AMÉM", referencia: "Apocalipse 22:21", dica: "'Assim seja' — a última palavra da Bíblia" },
  { palavra: "PÁSCOA", referencia: "Êxodo 12:11", dica: "Festa da libertação, com cordeiro e pães sem fermento" },
  { palavra: "SÁBADO", referencia: "Êxodo 20:8", dica: "Lembra-te deste dia para o santificar" },
  { palavra: "TRINDADE", referencia: "Mateus 28:19", dica: "Pai, Filho e Espírito Santo" },
  { palavra: "PARAÍSO", referencia: "Lucas 23:43", dica: "'Hoje estarás comigo' — promessa ao ladrão na cruz" },
  { palavra: "ASCENSÃO", referencia: "Atos 1:9", dica: "Jesus subiu aos céus diante dos discípulos" },

  // ===== Livros da Bíblia =====
  { palavra: "GÊNESIS", referencia: "Gênesis 1:1", dica: "O livro dos começos" },
  { palavra: "ÊXODO", referencia: "Êxodo 14:21", dica: "O livro da saída do Egito" },
  { palavra: "LEVÍTICO", referencia: "Levítico 19:2", dica: "O livro das leis sacerdotais: 'Sede santos'" },
  { palavra: "NÚMEROS", referencia: "Números 6:24", dica: "Livro dos censos no deserto" },
  { palavra: "JUÍZES", referencia: "Juízes 21:25", dica: "Livro da época em que 'cada um fazia o que achava certo'" },
  { palavra: "SALMO", referencia: "Salmos 23:1", dica: "'O Senhor é o meu pastor' está no de número 23" },
  { palavra: "CÂNTICOS", referencia: "Cantares 2:16", dica: "O livro de amor de Salomão" },
  { palavra: "ROMANOS", referencia: "Romanos 8:28", dica: "Carta de Paulo: 'todas as coisas cooperam para o bem'" },
  { palavra: "GÁLATAS", referencia: "Gálatas 5:22", dica: "Carta que lista o fruto do Espírito" },
  { palavra: "EFÉSIOS", referencia: "Efésios 6:11", dica: "Carta que descreve toda a armadura de Deus" },
  { palavra: "HEBREUS", referencia: "Hebreus 11:1", dica: "Carta com a galeria dos heróis da fé" },

  // ===== Objetos, animais e símbolos =====
  { palavra: "ARCA", referencia: "Gênesis 6:14", dica: "Noé a construiu de madeira de gofer" },
  { palavra: "MANÁ", referencia: "Êxodo 16:31", dica: "O pão que caía do céu no deserto" },
  { palavra: "SARÇA", referencia: "Êxodo 3:2", dica: "Ardia no fogo, mas não se consumia" },
  { palavra: "CAJADO", referencia: "Êxodo 4:2", dica: "Na mão de Moisés, virou serpente" },
  { palavra: "FUNDA", referencia: "1 Samuel 17:50", dica: "Arma de Davi contra o gigante" },
  { palavra: "ALTAR", referencia: "Gênesis 8:20", dica: "Noé construiu um ao sair da arca" },
  { palavra: "TENDA", referencia: "Hebreus 11:9", dica: "Habitação dos patriarcas, peregrinos na terra" },
  { palavra: "TEMPLO", referencia: "1 Reis 6:1", dica: "Salomão levou sete anos para construí-lo" },
  { palavra: "INCENSO", referencia: "Mateus 2:11", dica: "Um dos presentes dos magos" },
  { palavra: "MIRRA", referencia: "Mateus 2:11", dica: "Presente dos magos que apontava para o sacrifício" },
  { palavra: "OURO", referencia: "Mateus 2:11", dica: "Presente dos magos digno de um rei" },
  { palavra: "MAGOS", referencia: "Mateus 2:1", dica: "Vieram do oriente seguindo uma estrela" },
  { palavra: "ESTRELA", referencia: "Mateus 2:2", dica: "Guiou os magos até Belém" },
  { palavra: "AZEITE", referencia: "1 Reis 17:14", dica: "Não faltou na botija da viúva de Sarepta" },
  { palavra: "TÚNICA", referencia: "Gênesis 37:3", dica: "A de José tinha muitas cores" },
  { palavra: "POMBA", referencia: "Gênesis 8:11", dica: "Voltou à arca com uma folha de oliveira no bico" },
  { palavra: "CORDEIRO", referencia: "João 1:29", dica: "'Eis o... de Deus, que tira o pecado do mundo'" },
  { palavra: "SERPENTE", referencia: "Gênesis 3:1", dica: "A mais astuta das criaturas do campo" },
  { palavra: "OVELHA", referencia: "Lucas 15:4", dica: "O pastor deixa noventa e nove para buscar uma" },
  { palavra: "PASTOR", referencia: "Salmos 23:1", dica: "'O Senhor é o meu..., nada me faltará'" },
  { palavra: "REBANHO", referencia: "João 10:16", dica: "Haverá um só, e um só Pastor" },
  { palavra: "DESERTO", referencia: "Mateus 4:1", dica: "Jesus jejuou nele por quarenta dias" },
  { palavra: "JUMENTO", referencia: "Mateus 21:7", dica: "Jesus entrou em Jerusalém montado num" },
  { palavra: "TRIGO", referencia: "Mateus 13:25", dica: "O inimigo semeou joio no meio dele" },
  { palavra: "JOIO", referencia: "Mateus 13:30", dica: "Cresce junto com o trigo até a colheita" },
  { palavra: "MOSTARDA", referencia: "Mateus 13:31", dica: "O Reino é como um grão dela" },
  { palavra: "FERMENTO", referencia: "Mateus 13:33", dica: "Um pouco leveda toda a massa" },
  { palavra: "SEMENTE", referencia: "Lucas 8:11", dica: "Na parábola do semeador, é a Palavra de Deus" },
  { palavra: "VINHA", referencia: "Mateus 20:1", dica: "O dono saiu de madrugada para contratar trabalhadores" },
  { palavra: "VIDEIRA", referencia: "João 15:5", dica: "'Eu sou a..., vós sois os ramos'" },
  { palavra: "FIGUEIRA", referencia: "Mateus 21:19", dica: "Secou ao não dar frutos para Jesus" },
  { palavra: "OLIVEIRA", referencia: "Romanos 11:17", dica: "Os gentios foram enxertados nela" },
  { palavra: "PÉROLA", referencia: "Mateus 13:46", dica: "O comerciante vendeu tudo para comprar uma de grande valor" },
  { palavra: "TESOURO", referencia: "Mateus 6:21", dica: "Onde ele estiver, aí estará o teu coração" },
  { palavra: "TALENTO", referencia: "Mateus 25:25", dica: "O servo mau enterrou o seu" },
  { palavra: "DRACMA", referencia: "Lucas 15:8", dica: "A mulher varreu a casa para achar esta moeda perdida" },
  { palavra: "DENÁRIO", referencia: "Mateus 20:2", dica: "O salário de um dia de trabalho na vinha" },
  { palavra: "CANDEIA", referencia: "Mateus 5:15", dica: "Não se acende para pôr debaixo do alqueire" },
  { palavra: "PESCADOR", referencia: "Mateus 4:19", dica: "'Vinde após mim, e eu vos farei... de homens'" },
  { palavra: "GALO", referencia: "Mateus 26:34", dica: "Antes que cante, Pedro negaria três vezes" },
  { palavra: "ESPINHOS", referencia: "João 19:2", dica: "Os soldados teceram uma coroa deles" },
  { palavra: "CRUZ", referencia: "João 19:17", dica: "Jesus a carregou até o Gólgota" },
  { palavra: "SEPULCRO", referencia: "Mateus 28:6", dica: "Foi encontrado vazio no terceiro dia" },
  { palavra: "TROMBETA", referencia: "1 Coríntios 15:52", dica: "Ao seu último som, os mortos ressuscitarão" },
  { palavra: "TRONO", referencia: "Apocalipse 4:2", dica: "João viu um no céu, e Alguém assentado nele" },
  { palavra: "COROA", referencia: "2 Timóteo 4:8", dica: "A da justiça está reservada aos que amam a Sua vinda" },
  { palavra: "DRAGÃO", referencia: "Apocalipse 12:9", dica: "A antiga serpente lançada fora no Apocalipse" },
  { palavra: "ABISMO", referencia: "Apocalipse 20:3", dica: "Onde a serpente ficará presa por mil anos" },

  // ===== Grupos e funções =====
  { palavra: "LEVITA", referencia: "Números 3:12", dica: "Membro da tribo dedicada ao serviço do santuário" },
  { palavra: "FARISEU", referencia: "Lucas 18:11", dica: "Na parábola, orava agradecendo não ser como os outros" },
  { palavra: "SADUCEU", referencia: "Mateus 22:23", dica: "Grupo que não cria na ressurreição" },
  { palavra: "ESCRIBA", referencia: "Mateus 23:2", dica: "Copista e mestre da Lei" },
  { palavra: "ARCANJO", referencia: "Judas 1:9", dica: "Miguel é chamado assim" },
  { palavra: "QUERUBIM", referencia: "Gênesis 3:24", dica: "Guardou o caminho da árvore da vida com espada de fogo" },
  { palavra: "SERAFIM", referencia: "Isaías 6:2", dica: "Ser celestial de seis asas que clama 'Santo, Santo, Santo'" },
  { palavra: "ANJO", referencia: "Lucas 2:10", dica: "Anunciou aos pastores: 'Eis que vos trago boas-novas'" },
  { palavra: "SANTO", referencia: "1 Pedro 1:16", dica: "'Sede santos, porque eu sou...'" },
];
