export interface BiblicalWord {
  /** Forma exibida, com acentos */
  palavra: string;
  /** Referência bíblica */
  referencia: string;
  /** Dica/curiosidade revelada ao jogador */
  dica: string;
  /** Versículo (citação curta) exibido ao revelar a palavra */
  versiculo: string;
}

/**
 * Banco de palavras do modo diário (4 a 8 letras, sem contar acentos).
 * A ordem é embaralhada deterministicamente em daily.ts — adicionar
 * novas palavras ao FINAL da lista não altera os dias já sorteados.
 */
export const WORDS: BiblicalWord[] = [
  // ===== Personagens do Antigo Testamento =====
  { palavra: "ADÃO", referencia: "Gênesis 2:20", dica: "O primeiro homem, formado do pó da terra", versiculo: "“E Adão pôs nomes a todo o gado, e às aves dos céus, e a todo animal do campo.”" },
  { palavra: "CAIM", referencia: "Gênesis 4:8", dica: "Matou seu irmão por inveja", versiculo: "“E, estando eles no campo, se levantou Caim contra o seu irmão Abel.”" },
  { palavra: "ABEL", referencia: "Gênesis 4:4", dica: "Pastor de ovelhas cuja oferta agradou a Deus", versiculo: "“E Abel também trouxe dos primogênitos das suas ovelhas; e atentou o Senhor para Abel e para a sua oferta.”" },
  { palavra: "SETE", referencia: "Gênesis 4:25", dica: "Filho de Adão nascido depois da morte de Abel", versiculo: "“E chamou o seu nome Sete; porque, disse ela, Deus me deu outro filho em lugar de Abel.”" },
  { palavra: "ENOQUE", referencia: "Gênesis 5:24", dica: "Andou com Deus e foi arrebatado sem ver a morte", versiculo: "“E andou Enoque com Deus; e não apareceu mais, porquanto Deus para si o tomou.”" },
  { palavra: "ABRAÃO", referencia: "Gênesis 17:5", dica: "Pai de uma multidão de nações", versiculo: "“Não se chamará mais o teu nome Abrão, mas Abraão será o teu nome; porque por pai de muitas nações te tenho posto.”" },
  { palavra: "SARA", referencia: "Gênesis 17:15", dica: "Riu ao ouvir que teria um filho na velhice", versiculo: "“Não chamarás mais o seu nome Sarai, mas Sara será o seu nome.”" },
  { palavra: "AGAR", referencia: "Gênesis 16:1", dica: "Serva egípcia de Sara, mãe de Ismael", versiculo: "“Ora, Sarai tinha uma serva egípcia, cujo nome era Agar.”" },
  { palavra: "ISMAEL", referencia: "Gênesis 16:11", dica: "Filho de Abraão com a serva egípcia", versiculo: "“E chamarás o seu nome Ismael, porquanto o Senhor ouviu a tua aflição.”" },
  { palavra: "ISAQUE", referencia: "Gênesis 22:2", dica: "Filho da promessa, quase sacrificado no monte Moriá", versiculo: "“Toma agora o teu filho, o teu único filho, Isaque, a quem amas, e vai-te à terra de Moriá.”" },
  { palavra: "REBECA", referencia: "Gênesis 24:67", dica: "Deu de beber aos camelos e tornou-se esposa de Isaque", versiculo: "“E tomou a Rebeca, e ela lhe foi por mulher, e amou-a.”" },
  { palavra: "JACÓ", referencia: "Gênesis 28:12", dica: "Sonhou com uma escada que tocava o céu", versiculo: "“E sonhou: eis que era posta na terra uma escada cujo topo tocava nos céus.”" },
  { palavra: "ESAÚ", referencia: "Gênesis 25:25", dica: "Vendeu a primogenitura por um prato de lentilhas", versiculo: "“E saiu o primeiro ruivo, todo como um vestido cabeludo; por isso, chamaram o seu nome Esaú.”" },
  { palavra: "RAQUEL", referencia: "Gênesis 29:18", dica: "Jacó trabalhou catorze anos para se casar com ela", versiculo: "“Jacó amava a Raquel e disse: Sete anos te servirei por Raquel, tua filha menor.”" },
  { palavra: "LABÃO", referencia: "Gênesis 29:25", dica: "Sogro que enganou Jacó na noite do casamento", versiculo: "“Pela manhã, eis que era Lia; pelo que disse a Labão: Por que me enganaste?”" },
  { palavra: "JOSÉ", referencia: "Gênesis 37:3", dica: "Recebeu do pai uma túnica colorida e sonhava sonhos", versiculo: "“E Israel amava a José mais do que a todos os seus filhos e fez-lhe uma túnica de várias cores.”" },
  { palavra: "BENJAMIM", referencia: "Gênesis 35:18", dica: "O caçula dos doze filhos de Jacó", versiculo: "“Chamou o seu nome Benoni; mas seu pai lhe chamou Benjamim.”" },
  { palavra: "JUDÁ", referencia: "Gênesis 49:10", dica: "Tribo da qual descende o Messias", versiculo: "“O cetro não se arredará de Judá, nem o legislador dentre os seus pés, até que venha Siló.”" },
  { palavra: "LEVI", referencia: "Êxodo 32:26", dica: "Tribo separada para o serviço do santuário", versiculo: "“Quem é do Senhor venha até mim. Então, se ajuntaram a ele todos os filhos de Levi.”" },
  { palavra: "SIMEÃO", referencia: "Gênesis 34:25", dica: "Segundo filho de Jacó e Lia", versiculo: "“Simeão e Levi, irmãos de Diná, tomaram cada um a sua espada.”" },
  { palavra: "POTIFAR", referencia: "Gênesis 39:1", dica: "Oficial de Faraó que comprou José como escravo", versiculo: "“Potifar, oficial de Faraó, capitão da guarda, comprou-o da mão dos ismaelitas.”" },
  { palavra: "FARAÓ", referencia: "Êxodo 5:2", dica: "Rei do Egito que endureceu o coração", versiculo: "“Quem é o Senhor, cuja voz eu ouvirei, para deixar ir Israel?”" },
  { palavra: "MOISÉS", referencia: "Êxodo 2:10", dica: "Tirado das águas, libertou o povo de Israel do Egito", versiculo: "“E chamou o seu nome Moisés, e disse: Porque das águas o tenho tirado.”" },
  { palavra: "AARÃO", referencia: "Êxodo 4:14", dica: "Irmão de Moisés e primeiro sumo sacerdote", versiculo: "“Não é Arão, o levita, teu irmão? Eu sei que ele falará muito bem.”" },
  { palavra: "MIRIÃ", referencia: "Êxodo 15:20", dica: "Profetisa que cantou e dançou após a travessia do mar", versiculo: "“Então, Miriã, a profetisa, tomou o tamboril na sua mão, e todas as mulheres saíram atrás dela com tamboris e com danças.”" },
  { palavra: "JETRO", referencia: "Êxodo 18:1", dica: "Sogro de Moisés, sacerdote de Midiã", versiculo: "“Ora, ouviu Jetro, sacerdote de Midiã, sogro de Moisés, todas as coisas que Deus tinha feito.”" },
  { palavra: "ZÍPORA", referencia: "Êxodo 2:21", dica: "Esposa midianita de Moisés", versiculo: "“E ele deu a Moisés sua filha Zípora.”" },
  { palavra: "JOSUÉ", referencia: "Josué 1:9", dica: "Sucedeu Moisés e conquistou a terra prometida", versiculo: "“Esforça-te e tem bom ânimo; não temas, nem te espantes, porque o Senhor, teu Deus, é contigo por onde quer que andares.”" },
  { palavra: "CALEBE", referencia: "Números 13:30", dica: "Espia corajoso que confiou na promessa de Deus", versiculo: "“Então, Calebe fez calar o povo e disse: Certamente subiremos e a possuiremos em herança.”" },
  { palavra: "BALAÃO", referencia: "Números 22:28", dica: "Profeta repreendido pela própria jumenta", versiculo: "“Então, o Senhor abriu a boca da jumenta, a qual disse a Balaão: Que te fiz eu, que me espancaste estas três vezes?”" },
  { palavra: "RAABE", referencia: "Josué 2:1", dica: "Escondeu os espias em Jericó e foi salva", versiculo: "“E entraram na casa de uma mulher chamada Raabe, e pousaram ali.”" },
  { palavra: "DÉBORA", referencia: "Juízes 4:4", dica: "Profetisa e juíza que julgava debaixo de uma palmeira", versiculo: "“Débora, profetisa, julgava a Israel naquele tempo.”" },
  { palavra: "GIDEÃO", referencia: "Juízes 7:7", dica: "Venceu os midianitas com apenas trezentos homens", versiculo: "“Com estes trezentos homens que lamberam a água vos livrarei e darei os midianitas na tua mão.”" },
  { palavra: "SANSÃO", referencia: "Juízes 16:17", dica: "Sua força estava nos cabelos", versiculo: "“Nunca subiu navalha à minha cabeça; se viesse a ser rapado, ir-se-ia de mim a minha força.”" },
  { palavra: "DALILA", referencia: "Juízes 16:19", dica: "Descobriu o segredo da força de Sansão", versiculo: "“Então, ela o fez dormir sobre os seus joelhos e fez-lhe rapar as sete tranças do cabelo de sua cabeça.”" },
  { palavra: "RUTE", referencia: "Rute 1:16", dica: "Moabita fiel: 'aonde quer que fores, irei eu'", versiculo: "“Aonde quer que tu fores, irei eu; o teu povo é o meu povo, o teu Deus é o meu Deus.”" },
  { palavra: "NOEMI", referencia: "Rute 1:20", dica: "Sogra de Rute, pediu para ser chamada de Mara", versiculo: "“Não me chameis Noemi; chamai-me Mara, porque grande amargura me tem dado o Todo-Poderoso.”" },
  { palavra: "BOAZ", referencia: "Rute 2:1", dica: "Resgatador que se casou com Rute", versiculo: "“E tinha Noemi um parente de seu marido, homem valente e poderoso, e era o seu nome Boaz.”" },
  { palavra: "SAMUEL", referencia: "1 Samuel 3:10", dica: "Ouviu a voz de Deus ainda menino no templo", versiculo: "“E veio o Senhor e chamou: Samuel, Samuel. E disse Samuel: Fala, porque o teu servo ouve.”" },
  { palavra: "SAUL", referencia: "1 Samuel 9:2", dica: "O primeiro rei de Israel", versiculo: "“Desde os ombros para cima, sobressaía a todo o povo.”" },
  { palavra: "DAVI", referencia: "1 Samuel 17:45", dica: "Pastor que venceu um gigante com uma funda", versiculo: "“Tu vens a mim com espada, e com lança, e com escudo; porém eu venho a ti em nome do Senhor dos Exércitos.”" },
  { palavra: "GOLIAS", referencia: "1 Samuel 17:4", dica: "Gigante filisteu derrotado por um jovem pastor", versiculo: "“Então, saiu do arraial dos filisteus um homem guerreiro, cujo nome era Golias.”" },
  { palavra: "JESSÉ", referencia: "1 Samuel 16:1", dica: "Pai de Davi, morador de Belém", versiculo: "“Envia-te a Jessé, o belemita; porque dentre os seus filhos me tenho provido de um rei.”" },
  { palavra: "JÔNATAS", referencia: "1 Samuel 18:1", dica: "Filho de Saul e melhor amigo de Davi", versiculo: "“A alma de Jônatas se ligou com a alma de Davi; e Jônatas o amou como à sua própria alma.”" },
  { palavra: "MICAL", referencia: "1 Samuel 18:27", dica: "Filha de Saul, primeira esposa de Davi", versiculo: "“E Saul lhe deu sua filha Mical por mulher.”" },
  { palavra: "NATÃ", referencia: "2 Samuel 12:7", dica: "Profeta que confrontou Davi: 'Tu és este homem!'", versiculo: "“Então, disse Natã a Davi: Tu és este homem.”" },
  { palavra: "ABSALÃO", referencia: "2 Samuel 18:9", dica: "Filho rebelde de Davi, ficou preso pelos cabelos", versiculo: "“Se lhe prendeu a cabeça no carvalho, e ficou pendurado entre o céu e a terra.”" },
  { palavra: "SALOMÃO", referencia: "1 Reis 3:12", dica: "Pediu sabedoria a Deus e construiu o templo", versiculo: "“Eis que te dei um coração tão sábio e entendido, que antes de ti igual não houve.”" },
  { palavra: "ACABE", referencia: "1 Reis 16:30", dica: "Rei ímpio de Israel, marido de Jezabel", versiculo: "“E fez Acabe o que era mau aos olhos do Senhor, mais do que todos os que foram antes dele.”" },
  { palavra: "JEZABEL", referencia: "1 Reis 19:2", dica: "Rainha que perseguiu os profetas do Senhor", versiculo: "“Então, Jezabel mandou um mensageiro a Elias, dizendo: Assim me façam os deuses.”" },
  { palavra: "ELIAS", referencia: "1 Reis 18:38", dica: "Desafiou os profetas de Baal no monte Carmelo", versiculo: "“Então, caiu fogo do Senhor, e consumiu o holocausto, e a lenha, e as pedras.”" },
  { palavra: "ELISEU", referencia: "2 Reis 2:9", dica: "Pediu porção dobrada do espírito de seu mestre", versiculo: "“Peço-te que haja porção dobrada de teu espírito sobre mim.”" },
  { palavra: "NAAMÃ", referencia: "2 Reis 5:14", dica: "General sírio curado da lepra no rio Jordão", versiculo: "“Então, desceu e mergulhou no Jordão sete vezes; e a sua carne se tornou como a carne de um menino.”" },
  { palavra: "JOSIAS", referencia: "2 Reis 23:25", dica: "Rei menino que restaurou a adoração em Judá", versiculo: "“Antes dele, não houve rei semelhante, que se convertesse ao Senhor com todo o seu coração.”" },
  { palavra: "EZEQUIAS", referencia: "2 Reis 20:5", dica: "Rei que ganhou quinze anos a mais de vida", versiculo: "“Ouvi a tua oração e vi as tuas lágrimas; eis que eu te sararei.”" },
  { palavra: "ESDRAS", referencia: "Esdras 7:10", dica: "Escriba que ensinou a Lei ao povo no retorno do exílio", versiculo: "“Porque Esdras tinha preparado o seu coração para buscar a Lei do Senhor, e para a cumprir, e para ensinar.”" },
  { palavra: "NEEMIAS", referencia: "Neemias 2:17", dica: "Reconstruiu os muros de Jerusalém", versiculo: "“Vinde, pois, e reedifiquemos o muro de Jerusalém e não estejamos mais em opróbrio.”" },
  { palavra: "ESTER", referencia: "Ester 4:14", dica: "Rainha que salvou seu povo 'para um momento como este'", versiculo: "“E quem sabe se para tal tempo como este chegaste a este reino?”" },
  { palavra: "HAMÃ", referencia: "Ester 7:10", dica: "Tramou contra os judeus e morreu na própria forca", versiculo: "“Enforcaram, pois, a Hamã na forca que ele tinha preparado para Mardoqueu.”" },
  { palavra: "VASTI", referencia: "Ester 1:12", dica: "Rainha deposta antes de Ester", versiculo: "“Porém a rainha Vasti recusou vir conforme a palavra do rei.”" },
  { palavra: "CIRO", referencia: "Esdras 1:1", dica: "Rei persa que autorizou a volta dos judeus do exílio", versiculo: "“O Senhor despertou o espírito de Ciro, rei da Pérsia, e fez passar pregão por todo o seu reino.”" },
  { palavra: "ISAÍAS", referencia: "Isaías 6:8", dica: "Profeta que disse: 'Eis-me aqui, envia-me a mim'", versiculo: "“A quem enviarei, e quem há de ir por nós? Então, disse eu: Eis-me aqui, envia-me a mim.”" },
  { palavra: "JEREMIAS", referencia: "Jeremias 1:5", dica: "O profeta que chorava por Jerusalém", versiculo: "“Antes que te formasse no ventre, te conheci; e, antes que saísses da madre, te santifiquei.”" },
  { palavra: "EZEQUIEL", referencia: "Ezequiel 37:4", dica: "Profetizou a um vale de ossos secos", versiculo: "“Ossos secos, ouvi a palavra do Senhor.”" },
  { palavra: "DANIEL", referencia: "Daniel 6:22", dica: "Saiu ileso da cova dos leões", versiculo: "“O meu Deus enviou o seu anjo e fechou a boca dos leões, para que não me fizessem dano.”" },
  { palavra: "SADRAQUE", referencia: "Daniel 3:25", dica: "Um dos três jovens lançados na fornalha ardente", versiculo: "“Eu vejo quatro homens soltos, que andam passeando dentro do fogo, sem sofrer nenhum dano.”" },
  { palavra: "MESAQUE", referencia: "Daniel 3:25", dica: "Companheiro de Daniel salvo da fornalha", versiculo: "“Não vimos nós três homens atados lançados dentro do fogo?”" },
  { palavra: "ABEDNEGO", referencia: "Daniel 3:25", dica: "O terceiro jovem que não se curvou à estátua", versiculo: "“E o aspecto do quarto é semelhante ao Filho de Deus.”" },
  { palavra: "JONAS", referencia: "Jonas 1:17", dica: "Passou três dias no ventre de um grande peixe", versiculo: "“Deparou, pois, o Senhor um grande peixe; e esteve Jonas três dias e três noites nas entranhas do peixe.”" },
  { palavra: "OSEIAS", referencia: "Oseias 1:2", dica: "Profeta cujo casamento ilustrou o amor fiel de Deus", versiculo: "“O princípio da palavra do Senhor por Oseias.”" },
  { palavra: "JOEL", referencia: "Joel 2:28", dica: "Profetizou o derramamento do Espírito sobre toda carne", versiculo: "“E há de ser que, depois, derramarei o meu Espírito sobre toda a carne.”" },
  { palavra: "AMÓS", referencia: "Amós 1:1", dica: "Boiadeiro de Tecoa chamado a profetizar", versiculo: "“As palavras de Amós, que estava entre os pastores de Tecoa.”" },
  { palavra: "MIQUEIAS", referencia: "Miqueias 5:2", dica: "Anunciou que o Messias nasceria em Belém", versiculo: "“E tu, Belém Efrata, posto que pequena, de ti me sairá o que governará em Israel.”" },
  { palavra: "NAUM", referencia: "Naum 1:7", dica: "Profetizou contra Nínive: 'O Senhor é bom, uma fortaleza'", versiculo: "“O Senhor é bom, uma fortaleza no dia da angústia, e conhece os que confiam nele.”" },
  { palavra: "AGEU", referencia: "Ageu 1:8", dica: "Exortou o povo a reconstruir o templo", versiculo: "“Subi ao monte, e trazei madeira, e edificai a casa; e dela me agradarei.”" },
  { palavra: "SOFONIAS", referencia: "Sofonias 3:17", dica: "Profetizou que Deus se alegra sobre nós com cânticos", versiculo: "“O Senhor, teu Deus, está no meio de ti; ele se deleitará em ti com alegria e se regozijará em ti com júbilo.”" },
  { palavra: "ZACARIAS", referencia: "Zacarias 9:9", dica: "Viu o rei vindo humilde, montado num jumentinho", versiculo: "“Eis que o teu rei virá a ti, justo e salvador, pobre e montado sobre um jumento.”" },

  // ===== Personagens do Novo Testamento =====
  { palavra: "JESUS", referencia: "Mateus 1:21", dica: "O nome que está acima de todo nome", versiculo: "“E ela dará à luz um filho, e chamarás o seu nome Jesus, porque ele salvará o seu povo dos seus pecados.”" },
  { palavra: "MARIA", referencia: "Lucas 1:30", dica: "Achou graça diante de Deus e gerou o Salvador", versiculo: "“Maria, não temas, porque achaste graça diante de Deus.”" },
  { palavra: "MARTA", referencia: "Lucas 10:41", dica: "Ocupava-se com muitas coisas enquanto a irmã ouvia Jesus", versiculo: "“Marta, Marta, estás ansiosa e afadigada com muitas coisas, mas uma só é necessária.”" },
  { palavra: "PEDRO", referencia: "Mateus 16:18", dica: "A 'pedra' que negou Jesus três vezes antes do galo cantar", versiculo: "“Tu és Pedro, e sobre esta pedra edificarei a minha igreja.”" },
  { palavra: "ANDRÉ", referencia: "João 1:40", dica: "Pescador que levou seu irmão Simão até Jesus", versiculo: "“Era André, irmão de Simão Pedro, um dos dois que ouviram aquilo de João.”" },
  { palavra: "TIAGO", referencia: "Marcos 3:17", dica: "Filho de Zebedeu, um dos 'filhos do trovão'", versiculo: "“A Tiago, filho de Zebedeu, e a João pôs o nome de Boanerges, que significa Filhos do Trovão.”" },
  { palavra: "JOÃO", referencia: "João 13:23", dica: "O discípulo amado, autor do Apocalipse", versiculo: "“Um de seus discípulos, aquele a quem Jesus amava, estava reclinado no seio de Jesus.”" },
  { palavra: "FELIPE", referencia: "João 1:45", dica: "Disse a Natanael: 'Vem e vê'", versiculo: "“Filipe achou Natanael e disse-lhe: Havemos achado aquele de quem Moisés escreveu na Lei.”" },
  { palavra: "TOMÉ", referencia: "João 20:27", dica: "Só creu depois de ver as marcas dos cravos", versiculo: "“Põe aqui o teu dedo e vê as minhas mãos; e não sejas incrédulo, mas crente.”" },
  { palavra: "MATEUS", referencia: "Mateus 9:9", dica: "Cobrador de impostos chamado a seguir Jesus", versiculo: "“Viu um homem chamado Mateus, assentado na alfândega, e disse-lhe: Segue-me. E ele o seguiu.”" },
  { palavra: "JUDAS", referencia: "Mateus 26:15", dica: "Traiu o Mestre por trinta moedas de prata", versiculo: "“Que me quereis dar, e eu vo-lo entregarei? E eles lhe pesaram trinta moedas de prata.”" },
  { palavra: "SIMÃO", referencia: "Lucas 23:26", dica: "O cireneu obrigado a carregar a cruz de Jesus", versiculo: "“Pegaram num certo Simão, cireneu, e puseram-lhe a cruz às costas, para que a levasse após Jesus.”" },
  { palavra: "MARCOS", referencia: "Atos 12:25", dica: "Autor do segundo Evangelho, companheiro de Paulo e Barnabé", versiculo: "“Voltaram de Jerusalém, levando também consigo a João, que tinha por sobrenome Marcos.”" },
  { palavra: "LUCAS", referencia: "Colossenses 4:14", dica: "O médico amado que escreveu um Evangelho e Atos", versiculo: "“Saúda-vos Lucas, o médico amado.”" },
  { palavra: "PAULO", referencia: "Atos 13:9", dica: "De perseguidor a apóstolo dos gentios", versiculo: "“Saulo, que também se chama Paulo, cheio do Espírito Santo.”" },
  { palavra: "SAULO", referencia: "Atos 9:4", dica: "Ouviu no caminho de Damasco: 'por que me persegues?'", versiculo: "“Saulo, Saulo, por que me persegues?”" },
  { palavra: "BARNABÉ", referencia: "Atos 4:36", dica: "Seu nome significa 'filho da consolação'", versiculo: "“José, a quem os apóstolos chamavam Barnabé, que, traduzido, é Filho da Consolação.”" },
  { palavra: "SILAS", referencia: "Atos 16:25", dica: "Cantava louvores na prisão com Paulo à meia-noite", versiculo: "“Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam.”" },
  { palavra: "TIMÓTEO", referencia: "1 Timóteo 4:12", dica: "Jovem pastor: 'ninguém despreze a tua mocidade'", versiculo: "“Ninguém despreze a tua mocidade; mas sê o exemplo dos fiéis, na palavra, no trato, no amor.”" },
  { palavra: "TITO", referencia: "Tito 1:5", dica: "Recebeu carta de Paulo e organizou a igreja em Creta", versiculo: "“Por esta causa te deixei em Creta, para que pusesses em boa ordem as coisas que ainda restam.”" },
  { palavra: "ESTÊVÃO", referencia: "Atos 7:59", dica: "O primeiro mártir da igreja", versiculo: "“E apedrejaram a Estêvão, que em invocação dizia: Senhor Jesus, recebe o meu espírito.”" },
  { palavra: "ZAQUEU", referencia: "Lucas 19:4", dica: "Subiu numa árvore para ver Jesus passar", versiculo: "“Subiu a uma figueira brava para o ver, porque havia de passar por ali.”" },
  { palavra: "LÁZARO", referencia: "João 11:43", dica: "Saiu do túmulo depois de quatro dias", versiculo: "“Clamou com grande voz: Lázaro, sai para fora.”" },
  { palavra: "MADALENA", referencia: "João 20:16", dica: "A primeira a ver o Senhor ressuscitado", versiculo: "“Disse-lhe Jesus: Maria! Ela, voltando-se, disse-lhe: Raboni (que quer dizer Mestre).”" },
  { palavra: "HERODES", referencia: "Mateus 2:16", dica: "Rei que mandou matar os meninos de Belém", versiculo: "“Herodes mandou matar todos os meninos que havia em Belém, de dois anos para baixo.”" },
  { palavra: "PILATOS", referencia: "Mateus 27:24", dica: "Lavou as mãos diante da multidão", versiculo: "“Tomou água, lavou as mãos diante da multidão e disse: Estou inocente do sangue deste justo.”" },
  { palavra: "CAIFÁS", referencia: "João 18:14", dica: "Sumo sacerdote no julgamento de Jesus", versiculo: "“Ora, Caifás era quem tinha aconselhado aos judeus que convinha que um homem morresse pelo povo.”" },
  { palavra: "BARRABÁS", referencia: "Mateus 27:21", dica: "O prisioneiro solto no lugar de Jesus", versiculo: "“Qual dos dois quereis que eu vos solte? E eles disseram: Barrabás.”" },
  { palavra: "PRISCILA", referencia: "Atos 18:26", dica: "Com seu marido Áquila, ensinou o caminho a Apolo", versiculo: "“Priscila e Áquila o levaram consigo e lhe declararam mais pontualmente o caminho de Deus.”" },
  { palavra: "ÁQUILA", referencia: "Atos 18:2", dica: "Fazedor de tendas, marido de Priscila", versiculo: "“Achou um certo judeu por nome Áquila, com sua mulher Priscila.”" },
  { palavra: "LÍDIA", referencia: "Atos 16:14", dica: "Vendedora de púrpura, primeira convertida na Europa", versiculo: "“Uma certa mulher chamada Lídia, vendedora de púrpura; e o Senhor lhe abriu o coração.”" },
  { palavra: "DORCAS", referencia: "Atos 9:36", dica: "Ressuscitada por Pedro, fazia roupas para os pobres", versiculo: "“Havia em Jope uma discípula chamada Tabita, ou Dorcas, cheia de boas obras e esmolas.”" },
  { palavra: "CORNÉLIO", referencia: "Atos 10:1", dica: "Centurião que recebeu Pedro e o Espírito Santo", versiculo: "“Havia em Cesareia um varão chamado Cornélio, centurião, piedoso e temente a Deus.”" },
  { palavra: "ANANIAS", referencia: "Atos 9:17", dica: "Impôs as mãos sobre Saulo para que voltasse a ver", versiculo: "“Saulo, irmão, o Senhor me enviou para que tornes a ver e sejas cheio do Espírito Santo.”" },
  { palavra: "ONÉSIMO", referencia: "Filemom 1:10", dica: "Escravo fugitivo que se tornou irmão amado", versiculo: "“Peço-te por meu filho Onésimo, que gerei nas minhas prisões.”" },
  { palavra: "BATISTA", referencia: "Mateus 3:1", dica: "Apelido do João que pregava no deserto", versiculo: "“Naqueles dias, apareceu João Batista pregando no deserto da Judeia.”" },

  // ===== Lugares =====
  { palavra: "ÉDEN", referencia: "Gênesis 2:8", dica: "O jardim onde tudo começou", versiculo: "“E plantou o Senhor Deus um jardim no Éden, e pôs ali o homem que tinha formado.”" },
  { palavra: "BABEL", referencia: "Gênesis 11:9", dica: "Torre onde as línguas foram confundidas", versiculo: "“Por isso, se chamou o seu nome Babel, porquanto ali confundiu o Senhor a língua de toda a terra.”" },
  { palavra: "SODOMA", referencia: "Gênesis 19:24", dica: "Cidade destruída por fogo e enxofre", versiculo: "“Então, o Senhor fez chover enxofre e fogo sobre Sodoma e Gomorra.”" },
  { palavra: "CANAÃ", referencia: "Êxodo 3:8", dica: "Terra que mana leite e mel", versiculo: "“Para fazê-lo subir a uma terra boa e larga, a uma terra que mana leite e mel.”" },
  { palavra: "EGITO", referencia: "Êxodo 1:8", dica: "Terra da escravidão de Israel por 400 anos", versiculo: "“Levantou-se um novo rei sobre o Egito, que não conhecera a José.”" },
  { palavra: "GÓSEN", referencia: "Gênesis 47:27", dica: "Região do Egito onde Israel habitou", versiculo: "“Assim, habitou Israel na terra do Egito, na terra de Gósen; e nela cresceram e se multiplicaram.”" },
  { palavra: "SINAI", referencia: "Êxodo 19:20", dica: "Monte onde Moisés recebeu as tábuas da Lei", versiculo: "“E, descendo o Senhor sobre o monte Sinai, chamou o Senhor a Moisés ao cume do monte.”" },
  { palavra: "HOREBE", referencia: "Êxodo 3:1", dica: "O monte de Deus, onde a sarça ardia", versiculo: "“E levou o rebanho atrás do deserto e chegou ao monte de Deus, a Horebe.”" },
  { palavra: "MIDIÃ", referencia: "Êxodo 2:15", dica: "Terra para onde Moisés fugiu de Faraó", versiculo: "“Moisés fugiu de diante da face de Faraó e habitou na terra de Midiã.”" },
  { palavra: "MOABE", referencia: "Rute 1:1", dica: "Terra natal de Rute", versiculo: "“Um homem de Belém de Judá saiu a peregrinar nos campos de Moabe.”" },
  { palavra: "ARARATE", referencia: "Gênesis 8:4", dica: "Montes onde a arca repousou", versiculo: "“E a arca repousou, no sétimo mês, sobre os montes de Ararate.”" },
  { palavra: "JERICÓ", referencia: "Josué 6:20", dica: "Suas muralhas caíram ao som das trombetas", versiculo: "“O povo gritou, e o muro caiu abaixo; e o povo subiu à cidade.”" },
  { palavra: "BETEL", referencia: "Gênesis 28:19", dica: "'Casa de Deus', onde Jacó sonhou com a escada", versiculo: "“E chamou o nome daquele lugar Betel: este é a casa de Deus, e esta é a porta dos céus.”" },
  { palavra: "HEBROM", referencia: "Gênesis 23:19", dica: "Cidade onde Abraão sepultou Sara", versiculo: "“Sepultou Abraão a Sara, sua mulher, na cova do campo de Macpela, em Hebrom.”" },
  { palavra: "SIÃO", referencia: "Salmos 2:6", dica: "O monte santo, símbolo de Jerusalém", versiculo: "“Eu, porém, ungi o meu Rei sobre o meu santo monte Sião.”" },
  { palavra: "SAMARIA", referencia: "João 4:4", dica: "Região da mulher que conversou com Jesus junto ao poço", versiculo: "“E era-lhe necessário passar por Samaria.”" },
  { palavra: "BELÉM", referencia: "Mateus 2:1", dica: "A pequena cidade onde o Salvador nasceu", versiculo: "“E, tendo nascido Jesus em Belém da Judeia, eis que uns magos vieram do Oriente.”" },
  { palavra: "NAZARÉ", referencia: "Mateus 2:23", dica: "'Pode vir algo de bom de lá?'", versiculo: "“E habitou numa cidade chamada Nazaré, para que se cumprisse: Ele será chamado Nazareno.”" },
  { palavra: "GALILEIA", referencia: "Mateus 4:18", dica: "Região do mar onde Jesus chamou os pescadores", versiculo: "“E Jesus, andando junto ao mar da Galileia, viu dois irmãos que lançavam as redes ao mar.”" },
  { palavra: "JORDÃO", referencia: "Mateus 3:13", dica: "Rio onde Jesus foi batizado", versiculo: "“Então, veio Jesus da Galileia ter com João junto do Jordão, para ser batizado por ele.”" },
  { palavra: "CANÁ", referencia: "João 2:1", dica: "Cidade do primeiro milagre: água em vinho", versiculo: "“Ao terceiro dia, fizeram-se umas bodas em Caná da Galileia; e estava ali a mãe de Jesus.”" },
  { palavra: "GÓLGOTA", referencia: "João 19:17", dica: "'Lugar da Caveira', onde a cruz foi fincada", versiculo: "“Levando ele às costas a sua cruz, saiu para o lugar chamado Caveira, que em hebraico se chama Gólgota.”" },
  { palavra: "CALVÁRIO", referencia: "Lucas 23:33", dica: "Nome latino do monte da crucificação", versiculo: "“E, quando chegaram ao lugar chamado Caveira, ali o crucificaram.”" },
  { palavra: "EMAÚS", referencia: "Lucas 24:13", dica: "No caminho até lá, dois discípulos andaram com o Ressuscitado", versiculo: "“Naquele mesmo dia, dois deles iam para uma aldeia chamada Emaús, falando entre si de tudo o que havia sucedido.”" },
  { palavra: "DAMASCO", referencia: "Atos 9:3", dica: "Saulo foi transformado a caminho desta cidade", versiculo: "“Chegando perto de Damasco, subitamente o cercou um resplendor de luz do céu.”" },
  { palavra: "TARSO", referencia: "Atos 9:11", dica: "Cidade natal do apóstolo Paulo", versiculo: "“Pergunta por um homem de Tarso chamado Saulo; pois eis que ele está orando.”" },
  { palavra: "CORINTO", referencia: "Atos 18:1", dica: "Cidade grega que recebeu duas cartas de Paulo", versiculo: "“Depois disto, partiu Paulo de Atenas e chegou a Corinto.”" },
  { palavra: "ÉFESO", referencia: "Atos 19:1", dica: "Paulo viveu ali três anos; recebeu uma carta e um aviso no Apocalipse", versiculo: "“Paulo, tendo passado por todas as regiões superiores, chegou a Éfeso.”" },
  { palavra: "ROMA", referencia: "Atos 28:16", dica: "Capital do império, destino final de Paulo", versiculo: "“E, logo que chegamos a Roma, a Paulo se lhe permitiu morar à parte, com o soldado que o guardava.”" },
  { palavra: "PATMOS", referencia: "Apocalipse 1:9", dica: "Ilha onde João recebeu a revelação", versiculo: "“Eu, João, estava na ilha chamada Patmos, por causa da palavra de Deus e pelo testemunho de Jesus.”" },
  { palavra: "NÍNIVE", referencia: "Jonas 3:5", dica: "A grande cidade que se arrependeu com a pregação de Jonas", versiculo: "“E os homens de Nínive creram em Deus; e proclamaram um jejum e vestiram-se de saco.”" },

  // ===== Conceitos e termos =====
  { palavra: "DEUS", referencia: "Gênesis 1:1", dica: "No princípio, Ele criou os céus e a terra", versiculo: "“No princípio, criou Deus os céus e a terra.”" },
  { palavra: "AMOR", referencia: "1 Coríntios 13:13", dica: "A maior entre a fé e a esperança", versiculo: "“Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor.”" },
  { palavra: "VIDA", referencia: "João 14:6", dica: "Jesus é o caminho, a verdade e...", versiculo: "“Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.”" },
  { palavra: "VERBO", referencia: "João 1:1", dica: "No princípio era... e Ele se fez carne", versiculo: "“No princípio, era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.”" },
  { palavra: "GRAÇA", referencia: "Efésios 2:8", dica: "Pela qual somos salvos, mediante a fé", versiculo: "“Pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus.”" },
  { palavra: "GLÓRIA", referencia: "Romanos 11:36", dica: "A Ele seja dada para todo o sempre", versiculo: "“Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente.”" },
  { palavra: "PECADO", referencia: "Romanos 6:23", dica: "Seu salário é a morte", versiculo: "“Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna.”" },
  { palavra: "PERDÃO", referencia: "Mateus 18:22", dica: "Setenta vezes sete", versiculo: "“Não te digo que até sete, mas até setenta vezes sete.”" },
  { palavra: "ALIANÇA", referencia: "Gênesis 9:13", dica: "O arco-íris é o sinal da primeira", versiculo: "“Porei o meu arco nas nuvens, e será por sinal da aliança entre mim e a terra.”" },
  { palavra: "PROFETA", referencia: "Deuteronômio 18:18", dica: "Porta-voz de Deus ao povo", versiculo: "“Eis que lhes suscitarei um profeta do meio de seus irmãos e porei as minhas palavras na sua boca.”" },
  { palavra: "APÓSTOLO", referencia: "Efésios 4:11", dica: "'Enviado' — Jesus escolheu doze", versiculo: "“E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e doutores.”" },
  { palavra: "BATISMO", referencia: "Romanos 6:4", dica: "Sepultados com Cristo nas águas", versiculo: "“Fomos sepultados com ele pelo batismo na morte, para que andemos em novidade de vida.”" },
  { palavra: "ORAÇÃO", referencia: "1 Tessalonicenses 5:17", dica: "Orai sem cessar", versiculo: "“Orai sem cessar.”" },
  { palavra: "JEJUM", referencia: "Mateus 6:17", dica: "Quando praticares, unge a cabeça e lava o rosto", versiculo: "“Porém tu, quando jejuares, unge a cabeça e lava o rosto.”" },
  { palavra: "DÍZIMO", referencia: "Malaquias 3:10", dica: "Trazei-os todos à casa do tesouro", versiculo: "“Trazei todos os dízimos à casa do tesouro e provai-me nisto, diz o Senhor dos Exércitos.”" },
  { palavra: "LOUVOR", referencia: "Salmos 150:6", dica: "Tudo quanto tem fôlego, louve ao Senhor", versiculo: "“Tudo quanto tem fôlego louve ao Senhor. Louvai ao Senhor!”" },
  { palavra: "ADORAÇÃO", referencia: "João 4:24", dica: "Em espírito e em verdade", versiculo: "“Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.”" },
  { palavra: "MILAGRE", referencia: "João 2:11", dica: "O primeiro foi numa festa de casamento", versiculo: "“Jesus principiou assim os seus sinais em Caná da Galileia e manifestou a sua glória.”" },
  { palavra: "PARÁBOLA", referencia: "Mateus 13:34", dica: "Jesus ensinava as multidões por meio delas", versiculo: "“Tudo isso disse Jesus por parábolas à multidão; e nada lhes falava sem parábolas.”" },
  { palavra: "SALVAÇÃO", referencia: "Atos 4:12", dica: "Não há em nenhum outro nome", versiculo: "“E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, pelo qual devamos ser salvos.”" },
  { palavra: "REDENÇÃO", referencia: "Efésios 1:7", dica: "Temos por meio do Seu sangue", versiculo: "“Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça.”" },
  { palavra: "ESPÍRITO", referencia: "Atos 2:4", dica: "Desceu como línguas de fogo no Pentecostes", versiculo: "“E todos foram cheios do Espírito Santo e começaram a falar em outras línguas.”" },
  { palavra: "CRIAÇÃO", referencia: "Gênesis 1:31", dica: "Deus viu tudo o que fez, e era muito bom", versiculo: "“E viu Deus tudo quanto tinha feito, e eis que era muito bom.”" },
  { palavra: "DILÚVIO", referencia: "Gênesis 7:12", dica: "Quarenta dias e quarenta noites de chuva", versiculo: "“E houve chuva sobre a terra quarenta dias e quarenta noites.”" },
  { palavra: "MESSIAS", referencia: "João 4:25", dica: "O Ungido prometido, que em grego é 'Cristo'", versiculo: "“Eu sei que o Messias (que se chama o Cristo) vem; quando ele vier, nos anunciará tudo.”" },
  { palavra: "EMANUEL", referencia: "Mateus 1:23", dica: "Significa 'Deus conosco'", versiculo: "“E chamá-lo-ão pelo nome de Emanuel, que traduzido é: Deus conosco.”" },
  { palavra: "HOSANA", referencia: "Mateus 21:9", dica: "Grito da multidão na entrada triunfal", versiculo: "“Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor!”" },
  { palavra: "ALELUIA", referencia: "Salmos 146:1", dica: "Expressão de louvor: 'Louvai ao Senhor'", versiculo: "“Louvai ao Senhor! Ó minha alma, louva ao Senhor!”" },
  { palavra: "AMÉM", referencia: "Apocalipse 22:21", dica: "'Assim seja' — a última palavra da Bíblia", versiculo: "“A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém!”" },
  { palavra: "PÁSCOA", referencia: "Êxodo 12:11", dica: "Festa da libertação, com cordeiro e pães sem fermento", versiculo: "“Comê-lo-eis apressadamente; esta é a Páscoa do Senhor.”" },
  { palavra: "SÁBADO", referencia: "Êxodo 20:8", dica: "Lembra-te deste dia para o santificar", versiculo: "“Lembra-te do dia do sábado, para o santificar.”" },
  { palavra: "TRINDADE", referencia: "Mateus 28:19", dica: "Pai, Filho e Espírito Santo", versiculo: "“Batizando-as em nome do Pai, e do Filho, e do Espírito Santo.”" },
  { palavra: "PARAÍSO", referencia: "Lucas 23:43", dica: "'Hoje estarás comigo' — promessa ao ladrão na cruz", versiculo: "“Em verdade te digo que hoje estarás comigo no Paraíso.”" },
  { palavra: "ASCENSÃO", referencia: "Atos 1:9", dica: "Jesus subiu aos céus diante dos discípulos", versiculo: "“Vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o a seus olhos.”" },

  // ===== Livros da Bíblia =====
  { palavra: "GÊNESIS", referencia: "Gênesis 1:1", dica: "O livro dos começos", versiculo: "“No princípio, criou Deus os céus e a terra.”" },
  { palavra: "ÊXODO", referencia: "Êxodo 14:21", dica: "O livro da saída do Egito", versiculo: "“O Senhor fez retirar o mar, e as águas foram partidas.”" },
  { palavra: "LEVÍTICO", referencia: "Levítico 19:2", dica: "O livro das leis sacerdotais: 'Sede santos'", versiculo: "“Santos sereis, porque eu, o Senhor, vosso Deus, sou santo.”" },
  { palavra: "NÚMEROS", referencia: "Números 6:24", dica: "Livro dos censos no deserto", versiculo: "“O Senhor te abençoe e te guarde.”" },
  { palavra: "JUÍZES", referencia: "Juízes 21:25", dica: "Livro da época em que 'cada um fazia o que achava certo'", versiculo: "“Naqueles dias, não havia rei em Israel; porém cada um fazia o que parecia direito aos seus olhos.”" },
  { palavra: "SALMO", referencia: "Salmos 23:1", dica: "'O Senhor é o meu pastor' está no de número 23", versiculo: "“O Senhor é o meu pastor; nada me faltará.”" },
  { palavra: "CÂNTICOS", referencia: "Cantares 2:16", dica: "O livro de amor de Salomão", versiculo: "“O meu amado é meu, e eu sou dele.”" },
  { palavra: "ROMANOS", referencia: "Romanos 8:28", dica: "Carta de Paulo: 'todas as coisas cooperam para o bem'", versiculo: "“Todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.”" },
  { palavra: "GÁLATAS", referencia: "Gálatas 5:22", dica: "Carta que lista o fruto do Espírito", versiculo: "“Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança.”" },
  { palavra: "EFÉSIOS", referencia: "Efésios 6:11", dica: "Carta que descreve toda a armadura de Deus", versiculo: "“Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.”" },
  { palavra: "HEBREUS", referencia: "Hebreus 11:1", dica: "Carta com a galeria dos heróis da fé", versiculo: "“Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.”" },

  // ===== Objetos, animais e símbolos =====
  { palavra: "ARCA", referencia: "Gênesis 6:14", dica: "Noé a construiu de madeira de gofer", versiculo: "“Faze para ti uma arca de madeira de gofer; farás compartimentos na arca.”" },
  { palavra: "MANÁ", referencia: "Êxodo 16:31", dica: "O pão que caía do céu no deserto", versiculo: "“E chamou a casa de Israel o seu nome maná; e o seu sabor era como bolos de mel.”" },
  { palavra: "SARÇA", referencia: "Êxodo 3:2", dica: "Ardia no fogo, mas não se consumia", versiculo: "“E olhou, e eis que a sarça ardia no fogo, e a sarça não se consumia.”" },
  { palavra: "CAJADO", referencia: "Êxodo 4:2", dica: "Na mão de Moisés, virou serpente", versiculo: "“E o Senhor disse: Que é isso na tua mão? E ele disse: Uma vara.”" },
  { palavra: "FUNDA", referencia: "1 Samuel 17:50", dica: "Arma de Davi contra o gigante", versiculo: "“Assim, Davi prevaleceu contra o filisteu com uma funda e com uma pedra.”" },
  { palavra: "ALTAR", referencia: "Gênesis 8:20", dica: "Noé construiu um ao sair da arca", versiculo: "“E edificou Noé um altar ao Senhor e ofereceu holocaustos sobre o altar.”" },
  { palavra: "TENDA", referencia: "Hebreus 11:9", dica: "Habitação dos patriarcas, peregrinos na terra", versiculo: "“Pela fé, habitou na terra da promessa, como em terra alheia, morando em tendas com Isaque e Jacó.”" },
  { palavra: "TEMPLO", referencia: "1 Reis 6:1", dica: "Salomão levou sete anos para construí-lo", versiculo: "“No ano quarto do reinado de Salomão, começou ele a edificar a casa do Senhor.”" },
  { palavra: "INCENSO", referencia: "Mateus 2:11", dica: "Um dos presentes dos magos", versiculo: "“E, abrindo os seus tesouros, ofertaram-lhe dádivas: ouro, incenso e mirra.”" },
  { palavra: "MIRRA", referencia: "Mateus 2:11", dica: "Presente dos magos que apontava para o sacrifício", versiculo: "“E, abrindo os seus tesouros, ofertaram-lhe dádivas: ouro, incenso e mirra.”" },
  { palavra: "OURO", referencia: "Mateus 2:11", dica: "Presente dos magos digno de um rei", versiculo: "“E, abrindo os seus tesouros, ofertaram-lhe dádivas: ouro, incenso e mirra.”" },
  { palavra: "MAGOS", referencia: "Mateus 2:1", dica: "Vieram do oriente seguindo uma estrela", versiculo: "“Eis que uns magos vieram do Oriente a Jerusalém.”" },
  { palavra: "ESTRELA", referencia: "Mateus 2:2", dica: "Guiou os magos até Belém", versiculo: "“Vimos a sua estrela no Oriente e viemos a adorá-lo.”" },
  { palavra: "AZEITE", referencia: "1 Reis 17:14", dica: "Não faltou na botija da viúva de Sarepta", versiculo: "“A farinha da panela não se acabará, e o azeite da botija não faltará.”" },
  { palavra: "TÚNICA", referencia: "Gênesis 37:3", dica: "A de José tinha muitas cores", versiculo: "“E Israel amava a José mais do que a todos os seus filhos e fez-lhe uma túnica de várias cores.”" },
  { palavra: "POMBA", referencia: "Gênesis 8:11", dica: "Voltou à arca com uma folha de oliveira no bico", versiculo: "“E a pomba voltou a ele à tarde; e eis, arrancada, uma folha de oliveira no seu bico.”" },
  { palavra: "CORDEIRO", referencia: "João 1:29", dica: "'Eis o... de Deus, que tira o pecado do mundo'", versiculo: "“Eis o Cordeiro de Deus, que tira o pecado do mundo.”" },
  { palavra: "SERPENTE", referencia: "Gênesis 3:1", dica: "A mais astuta das criaturas do campo", versiculo: "“Ora, a serpente era mais astuta que todas as alimárias do campo que o Senhor Deus tinha feito.”" },
  { palavra: "OVELHA", referencia: "Lucas 15:4", dica: "O pastor deixa noventa e nove para buscar uma", versiculo: "“Que homem dentre vós, tendo cem ovelhas e perdendo uma delas, não deixa as noventa e nove e não vai após a perdida?”" },
  { palavra: "PASTOR", referencia: "Salmos 23:1", dica: "'O Senhor é o meu..., nada me faltará'", versiculo: "“O Senhor é o meu pastor; nada me faltará.”" },
  { palavra: "REBANHO", referencia: "João 10:16", dica: "Haverá um só, e um só Pastor", versiculo: "“Haverá um rebanho e um Pastor.”" },
  { palavra: "DESERTO", referencia: "Mateus 4:1", dica: "Jesus jejuou nele por quarenta dias", versiculo: "“Então, foi conduzido Jesus pelo Espírito ao deserto, para ser tentado pelo diabo.”" },
  { palavra: "JUMENTO", referencia: "Mateus 21:7", dica: "Jesus entrou em Jerusalém montado num", versiculo: "“Trouxeram a jumenta e o jumentinho, e sobre eles puseram as suas vestes.”" },
  { palavra: "TRIGO", referencia: "Mateus 13:25", dica: "O inimigo semeou joio no meio dele", versiculo: "“Mas, dormindo os homens, veio o seu inimigo, e semeou joio no meio do trigo, e retirou-se.”" },
  { palavra: "JOIO", referencia: "Mateus 13:30", dica: "Cresce junto com o trigo até a colheita", versiculo: "“Deixai crescer ambos juntos até à ceifa; e, por ocasião da ceifa, colhei primeiro o joio.”" },
  { palavra: "MOSTARDA", referencia: "Mateus 13:31", dica: "O Reino é como um grão dela", versiculo: "“O Reino dos céus é semelhante ao grão de mostarda que o homem semeou no seu campo.”" },
  { palavra: "FERMENTO", referencia: "Mateus 13:33", dica: "Um pouco leveda toda a massa", versiculo: "“O Reino dos céus é semelhante ao fermento que uma mulher introduz em três medidas de farinha.”" },
  { palavra: "SEMENTE", referencia: "Lucas 8:11", dica: "Na parábola do semeador, é a Palavra de Deus", versiculo: "“Esta é, pois, a parábola: a semente é a palavra de Deus.”" },
  { palavra: "VINHA", referencia: "Mateus 20:1", dica: "O dono saiu de madrugada para contratar trabalhadores", versiculo: "“O Reino dos céus é semelhante a um pai de família que saiu de madrugada a assalariar trabalhadores para a sua vinha.”" },
  { palavra: "VIDEIRA", referencia: "João 15:5", dica: "'Eu sou a..., vós sois os ramos'", versiculo: "“Eu sou a videira, vós, as varas; quem está em mim, e eu nele, este dá muito fruto.”" },
  { palavra: "FIGUEIRA", referencia: "Mateus 21:19", dica: "Secou ao não dar frutos para Jesus", versiculo: "“Nunca mais nasça fruto de ti! E a figueira secou imediatamente.”" },
  { palavra: "OLIVEIRA", referencia: "Romanos 11:17", dica: "Os gentios foram enxertados nela", versiculo: "“Foste enxertado e feito participante da raiz e da seiva da oliveira.”" },
  { palavra: "PÉROLA", referencia: "Mateus 13:46", dica: "O comerciante vendeu tudo para comprar uma de grande valor", versiculo: "“Encontrando uma pérola de grande valor, foi, vendeu tudo quanto tinha e comprou-a.”" },
  { palavra: "TESOURO", referencia: "Mateus 6:21", dica: "Onde ele estiver, aí estará o teu coração", versiculo: "“Porque onde estiver o vosso tesouro, aí estará também o vosso coração.”" },
  { palavra: "TALENTO", referencia: "Mateus 25:25", dica: "O servo mau enterrou o seu", versiculo: "“E, atemorizado, escondi na terra o teu talento; aqui tens o que é teu.”" },
  { palavra: "DRACMA", referencia: "Lucas 15:8", dica: "A mulher varreu a casa para achar esta moeda perdida", versiculo: "“Qual a mulher que, tendo dez dracmas e perdendo uma, não acende a candeia, e varre a casa, e busca até a achar?”" },
  { palavra: "DENÁRIO", referencia: "Mateus 20:2", dica: "O salário de um dia de trabalho na vinha", versiculo: "“Ajustou com os trabalhadores um denário por dia e mandou-os para a sua vinha.”" },
  { palavra: "CANDEIA", referencia: "Mateus 5:15", dica: "Não se acende para pôr debaixo do alqueire", versiculo: "“Nem se acende a candeia para a colocar debaixo do alqueire, mas no velador, e dá luz a todos que estão na casa.”" },
  { palavra: "PESCADOR", referencia: "Mateus 4:19", dica: "'Vinde após mim, e eu vos farei... de homens'", versiculo: "“Vinde após mim, e eu vos farei pescadores de homens.”" },
  { palavra: "GALO", referencia: "Mateus 26:34", dica: "Antes que cante, Pedro negaria três vezes", versiculo: "“Em verdade te digo que, nesta mesma noite, antes que o galo cante, três vezes me negarás.”" },
  { palavra: "ESPINHOS", referencia: "João 19:2", dica: "Os soldados teceram uma coroa deles", versiculo: "“E os soldados, tecendo uma coroa de espinhos, lha puseram sobre a cabeça.”" },
  { palavra: "CRUZ", referencia: "João 19:17", dica: "Jesus a carregou até o Gólgota", versiculo: "“E, levando ele às costas a sua cruz, saiu para o lugar chamado Caveira.”" },
  { palavra: "SEPULCRO", referencia: "Mateus 28:6", dica: "Foi encontrado vazio no terceiro dia", versiculo: "“Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.”" },
  { palavra: "TROMBETA", referencia: "1 Coríntios 15:52", dica: "Ao seu último som, os mortos ressuscitarão", versiculo: "“Num momento, num abrir e fechar de olhos, ante a última trombeta, os mortos ressuscitarão incorruptíveis.”" },
  { palavra: "TRONO", referencia: "Apocalipse 4:2", dica: "João viu um no céu, e Alguém assentado nele", versiculo: "“Eis que um trono estava posto no céu, e um assentado sobre o trono.”" },
  { palavra: "COROA", referencia: "2 Timóteo 4:8", dica: "A da justiça está reservada aos que amam a Sua vinda", versiculo: "“Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia.”" },
  { palavra: "DRAGÃO", referencia: "Apocalipse 12:9", dica: "A antiga serpente lançada fora no Apocalipse", versiculo: "“E foi precipitado o grande dragão, a antiga serpente, chamada o diabo e Satanás.”" },
  { palavra: "ABISMO", referencia: "Apocalipse 20:3", dica: "Onde a serpente ficará presa por mil anos", versiculo: "“E lançou-o no abismo, e ali o encerrou, para que mais não engane as nações.”" },

  // ===== Grupos e funções =====
  { palavra: "LEVITA", referencia: "Números 3:12", dica: "Membro da tribo dedicada ao serviço do santuário", versiculo: "“Eis que tenho tomado os levitas do meio dos filhos de Israel; meus serão os levitas.”" },
  { palavra: "FARISEU", referencia: "Lucas 18:11", dica: "Na parábola, orava agradecendo não ser como os outros", versiculo: "“O fariseu, estando em pé, orava assim: Ó Deus, graças te dou, porque não sou como os demais homens.”" },
  { palavra: "SADUCEU", referencia: "Mateus 22:23", dica: "Grupo que não cria na ressurreição", versiculo: "“No mesmo dia, chegaram junto dele os saduceus, que dizem não haver ressurreição.”" },
  { palavra: "ESCRIBA", referencia: "Mateus 23:2", dica: "Copista e mestre da Lei", versiculo: "“Na cadeira de Moisés, estão assentados os escribas e fariseus.”" },
  { palavra: "ARCANJO", referencia: "Judas 1:9", dica: "Miguel é chamado assim", versiculo: "“Mas o arcanjo Miguel, quando contendia com o diabo, disse: O Senhor te repreenda.”" },
  { palavra: "QUERUBIM", referencia: "Gênesis 3:24", dica: "Guardou o caminho da árvore da vida com espada de fogo", versiculo: "“E, havendo lançado fora o homem, pôs querubins ao oriente do jardim do Éden e uma espada inflamada.”" },
  { palavra: "SERAFIM", referencia: "Isaías 6:2", dica: "Ser celestial de seis asas que clama 'Santo, Santo, Santo'", versiculo: "“Os serafins clamavam uns aos outros: Santo, Santo, Santo é o Senhor dos Exércitos.”" },
  { palavra: "ANJO", referencia: "Lucas 2:10", dica: "Anunciou aos pastores: 'Eis que vos trago boas-novas'", versiculo: "“E o anjo lhes disse: Não temais, porque eis aqui vos trago novas de grande alegria.”" },
  { palavra: "SANTO", referencia: "1 Pedro 1:16", dica: "'Sede santos, porque eu sou...'", versiculo: "“Porquanto escrito está: Sede santos, porque eu sou santo.”" },
];
